#!/bin/sh

TARGET_SCRIPT="drivertest.sh"
# Add the name of your target script here

echo "Running Monitoring Script"
while true; do
    if ! ps aux | grep -q [d]rivertest.sh ; then
        :

    else
        # Pause the target script
        if ps aux | grep -q [d]rivertest.sh  >/dev/null; then
            echo "Will restart the aesdSocket ..."

            ps aux | grep [a]esd
            kill -9  $(ps aux | grep aesdsocket | grep -v grep | awk '{print $1}')  

            ps aux | grep [d]rivertest.sh
            ps aux | grep [a]esd
            /usr/bin/aesdchar_unload 
            
            echo "########## Loaded driver Back###########"
	    ps aux | grep [d]rivertest.sh
	    ps aux | grep [a]esd
	    ps aux | grep [Ss]ocket
            /usr/bin/aesdchar_load &
            /usr/bin/aesdsocket -d 
            echo "########## Starting AESD Back###########"
            

            ps aux | grep [a]esd &

            exit  # Exit the script immediately after starting background processes
        fi
    fi
    usleep 10000  # Adjust the sleep interval as needed
done &

